add failing test cases
when we couldn't select any archive with pointCount <= maxPoints,
we forget to turn on runtime consolidation.
the case where metrics have different raw bands is the only case where
the runtime consolidation logic is triggered, to handle that case.
But in the case where the raw intervals are the same (most common for
read queries), runtime consolidation is not enabled, which is extra
severe if there are no rollups enabled, all points will be returned.

--- FAIL: TestAlignRequests (0.00s)
	dataprocessor_test.go:674: testcase 12, request 0:
		expected: a 0 - 31536000 . points <= 1000. AverageConsolidator - archive 3, rawInt 10, archInt 21600, outInt 43200, aggNum 2
		     got: a 0 - 31536000 . points <= 1000. AverageConsolidator - archive 3, rawInt 10, archInt 21600, outInt 21600, aggNum 1
	dataprocessor_test.go:674: testcase 12, request 1:
		expected: b 0 - 31536000 . points <= 1000. AverageConsolidator - archive 3, rawInt 30, archInt 21600, outInt 43200, aggNum 2
		     got: b 0 - 31536000 . points <= 1000. AverageConsolidator - archive 3, rawInt 30, archInt 21600, outInt 21600, aggNum 1
	dataprocessor_test.go:674: testcase 12, request 2:
		expected: c 0 - 31536000 . points <= 1000. AverageConsolidator - archive 3, rawInt 60, archInt 21600, outInt 43200, aggNum 2
		     got: c 0 - 31536000 . points <= 1000. AverageConsolidator - archive 3, rawInt 60, archInt 21600, outInt 21600, aggNum 1
	dataprocessor_test.go:674: testcase 14, request 0:
		expected: a 0 - 31536000 . points <= 1000. AverageConsolidator - archive 0, rawInt 30, archInt 30, outInt 31560, aggNum 1052
		     got: a 0 - 31536000 . points <= 1000. AverageConsolidator - archive 0, rawInt 30, archInt 30, outInt 30, aggNum 1
	dataprocessor_test.go:674: testcase 14, request 1:
		expected: b 0 - 31536000 . points <= 1000. AverageConsolidator - archive 0, rawInt 30, archInt 30, outInt 31560, aggNum 1052
		     got: b 0 - 31536000 . points <= 1000. AverageConsolidator - archive 0, rawInt 30, archInt 30, outInt 30, aggNum 1
	dataprocessor_test.go:674: testcase 14, request 2:
		expected: c 0 - 31536000 . points <= 1000. AverageConsolidator - archive 0, rawInt 30, archInt 30, outInt 31560, aggNum 1052
		     got: c 0 - 31536000 . points <= 1000. AverageConsolidator - archive 0, rawInt 30, archInt 30, outInt 30, aggNum 1
FAIL
exit status 1
FAIL	github.com/raintank/raintank-metric/metric_tank	0.004s